### ISSUE TITLE
Does version 2 support retina versions of assets/images?

### ISSUE THREAD

**Issue by CaptainChemist** [jhnvz/retina_rails#55]
I am trying to figure out how to get retina versions of image.jpg and image@2x.jpg type files that I have sitting in my assets -> images folder.  Does this gem support those or do they need to be entered into the database with paperclip? As an example, how do I convert this over:

<%= link_to image_tag("logo.png", :alt =>"logo", :role => 'banner', size: "257x35", :id => 'home'), main_app.root_path %>

(I am particularly worried about attributes like :alt, :role, :id which are not specified as valid settings in the retina_image_tag variant. Do I just append them with a different function?)

Thanks for the great gem!

**Comment by jhnvz** [comment]
I wouldn't add those to the database. I'd just use the @2x version by default and set the height and width attributes yourself since you know the dimensions e.g. `image_tag 'image.jpg', :width => 257, :height => 35` for a 514x70 image. See http://www.netvlies.nl/blog/design-interactie/retina-revolution for optimal compression). 

An other option would be to use an image swapping solution (the one we abandoned since version 2) on retina supported devices like http://imulus.github.io/retinajs/ or https://github.com/jhnvz/jquery-retina.

The `retina_image_tag` simply accepts the same options as `image_tag`: `retina_image_tag @user, :image, :small, :default => [50, 40], :alt =>"logo", :role => 'banner', :id => 'home'`. See https://github.com/jhnvz/retina_rails/blob/master/lib/retina_rails/helpers.rb#L36 and https://github.com/jhnvz/retina_rails/blob/master/spec/helpers_spec.rb#L89
